// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDQ4tbaYZWo_BOaQiqC9lxk8dgT9Kh1vI',
    appId: '1:122243161585:web:66f7334a98b7cac74e3850',
    messagingSenderId: '122243161585',
    projectId: 'chaton-c55c2',
    authDomain: 'chaton-c55c2.firebaseapp.com',
    storageBucket: 'chaton-c55c2.appspot.com',
    measurementId: 'G-DC82FFJ44Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwC8BFuAjflcKqIiAd-rnz3EY7VlbdQOU',
    appId: '1:122243161585:android:3089cc6da78b86924e3850',
    messagingSenderId: '122243161585',
    projectId: 'chaton-c55c2',
    storageBucket: 'chaton-c55c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFkkbe-RZ0XCgWFWrsRbcXsGlbXDHc4Z8',
    appId: '1:122243161585:ios:d51ef1ac92f9c04f4e3850',
    messagingSenderId: '122243161585',
    projectId: 'chaton-c55c2',
    storageBucket: 'chaton-c55c2.appspot.com',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFkkbe-RZ0XCgWFWrsRbcXsGlbXDHc4Z8',
    appId: '1:122243161585:ios:30e32cd2b254a0504e3850',
    messagingSenderId: '122243161585',
    projectId: 'chaton-c55c2',
    storageBucket: 'chaton-c55c2.appspot.com',
    iosBundleId: 'com.example.flutterFinal.RunnerTests',
  );
}
